"""Cookie import / export in multiple formats.

Supported formats:
  - **Netscape** ``cookies.txt`` — universal format used by curl/wget/most
    antidetect tools, including AdsPower's "Import cookies" UI.
  - **Playwright/Chrome DevTools JSON** — list of cookie dicts matching
    ``browser_context.add_cookies()`` schema.
  - **AdsPower ``.adb`` profile directory** — bundled tarball/folder
    containing ``Default/Cookies`` (SQLite) + ``Local Storage`` etc.

Output: a normalised list of cookie dicts ready for ``add_cookies``.

Netscape format reference:
    # Netscape HTTP Cookie File
    # https://curl.haxx.ru/rfc/cookie_spec.html
    # This file was generated by libcurl! Edit at your own risk.

    domain  flag  path  secure  expiration  name  value

    domain   TRUE   /      FALSE  9999999999  foo   bar
"""
from __future__ import annotations

import json
import sqlite3
import tarfile
import zipfile
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Union


@dataclass
class Cookie:
    name: str
    value: str
    domain: str = ""
    path: str = "/"
    expires: float = -1  # -1 = session cookie (matches Playwright)
    http_only: bool = False
    secure: bool = False
    same_site: str = "Lax"  # "Strict" | "Lax" | "None"

    def to_playwright(self) -> Dict[str, Any]:
        out: Dict[str, Any] = {
            "name": self.name,
            "value": self.value,
            "path": self.path,
            "expires": self.expires,
            "httpOnly": self.http_only,
            "secure": self.secure,
            "sameSite": self.same_site,
        }
        # Playwright wants "url" OR "domain"+"path". We always pass domain.
        # Domain may include a leading dot (Netscape). Playwright accepts that.
        if self.domain:
            out["domain"] = self.domain
        return out


# ---------------------------------------------------------------------------
# Normalisation helpers
# ---------------------------------------------------------------------------


def _normalize_samesite(s: Optional[str]) -> str:
    if not s:
        return "Lax"
    s = s.lower().strip()
    if s in ("strict", "lax", "none"):
        return s.capitalize()
    if "no" in s:  # "no same-site" → None
        return "None"
    return "Lax"


def _cookie_from_dict(d: Dict[str, Any]) -> Cookie:
    """Build a Cookie from a generic dict (CDP / Playwright / AdsPower)."""
    return Cookie(
        name=str(d.get("name", "")),
        value=str(d.get("value", "")),
        domain=str(d.get("domain", "") or d.get("host", "") or ""),
        path=str(d.get("path", "/")),
        expires=float(d.get("expires") or d.get("expirationDate") or -1),
        http_only=bool(d.get("httpOnly") or d.get("http_only") or False),
        secure=bool(d.get("secure", False)),
        same_site=_normalize_samesite(d.get("sameSite") or d.get("same_site")),
    )


# ---------------------------------------------------------------------------
# Format parsers
# ---------------------------------------------------------------------------


def import_cookies_netscape(text: str) -> List[Cookie]:
    """Parse a Netscape cookies.txt file (or ``str`` contents) into Cookies."""
    out: List[Cookie] = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or line.startswith("//"):
            continue
        parts = line.split("\t")
        if len(parts) < 7:
            # Some variants are space-separated — try a relaxed split
            parts = line.split()
            if len(parts) < 7:
                continue
        try:
            domain = parts[0]
            # Netscape flag: TRUE = include subdomains. We don't need to enforce,
            # Playwright ignores it. Strip leading dot if present.
            # path = parts[2], secure = parts[3] (TRUE/FALSE), expires = parts[4]
            secure = parts[3].upper() == "TRUE"
            try:
                expires = float(parts[4])
            except ValueError:
                expires = -1
            name = parts[5]
            value = parts[6]
            out.append(
                Cookie(
                    name=name,
                    value=value,
                    domain=domain,
                    path=parts[2] or "/",
                    expires=expires,
                    secure=secure,
                )
            )
        except (IndexError, ValueError):
            continue
    return out


def import_cookies_json(data: Union[str, List[Dict[str, Any]]]) -> List[Cookie]:
    """Parse a Playwright/ChromeDevTools JSON cookie list.

    Accepts either a JSON string or an already-decoded list of dicts.
    """
    if isinstance(data, str):
        data = json.loads(data)
    out: List[Cookie] = []
    if not isinstance(data, list):
        raise ValueError("JSON cookies must be a list of dicts")
    for d in data:
        if isinstance(d, dict):
            out.append(_cookie_from_dict(d))
    return out


def import_adspower_profile(adb_path: Union[str, Path]) -> List[Cookie]:
    """Import cookies from an AdsPower ``.adb`` profile bundle.

    AdsPower exports profiles either as a folder or a ``.zip`` / ``.tar.gz``.
    Inside, Chrome stores cookies at ``<profile>/Default/Cookies`` (SQLite).

    Returns the cookie list. Local Storage / IndexedDB are NOT extracted here
    (those would need a separate pass — see ``prepare_adspower_import``).
    """
    p = Path(adb_path)
    if not p.exists():
        raise FileNotFoundError(p)

    cookies_db: Optional[Path] = None
    extracted_to: Optional[Path] = None

    try:
        if p.is_file() and p.suffix.lower() == ".zip":
            # Extract to a temp dir (kept alive until we're done reading)
            import tempfile
            tmp = tempfile.mkdtemp(prefix="adshield_adb_")
            extracted_to = Path(tmp)
            with zipfile.ZipFile(p, "r") as zf:
                zf.extractall(tmp)
            cookies_db = _find_cookies_db(Path(tmp))
        elif p.is_file() and (p.suffix.lower() in (".tar", ".tgz") or p.name.endswith(".tar.gz")):
            import tempfile
            tmp = tempfile.mkdtemp(prefix="adshield_adb_")
            extracted_to = Path(tmp)
            with tarfile.open(p, "r:*") as tf:
                tf.extractall(tmp)
            cookies_db = _find_cookies_db(Path(tmp))
        elif p.is_dir():
            cookies_db = _find_cookies_db(p)
        else:
            # Single Cookies sqlite file?
            if p.suffix.lower() in (".db", ".sqlite", ""):
                cookies_db = p
    except Exception:
        # If extraction or locating failed, leave cookies_db None
        cookies_db = None

    if cookies_db is None or not cookies_db.exists():
        return []

    # Cookies table schema (Chrome ≥ v24): name, value, host_key, path, expires_utc,
    # is_secure, is_httponly, samesite, source_scheme, source_port, last_access_utc, ...
    # Try to open in RO mode first; fall back to a private temp copy if locked.
    conn = None
    tmp_copy: Optional[Path] = None
    try:
        try:
            conn = sqlite3.connect(f"file:{cookies_db}?mode=ro", uri=True)
        except sqlite3.OperationalError:
            # File might be locked; copy it to a temp file and open that.
            import tempfile, shutil
            tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".db")
            tmp.close()
            shutil.copy2(cookies_db, tmp.name)
            tmp_copy = Path(tmp.name)
            conn = sqlite3.connect(str(tmp_copy))
        out = _read_cookies_from_conn(conn)
    finally:
        if conn is not None:
            try:
                conn.close()
            except Exception:
                pass
        if tmp_copy is not None:
            try:
                tmp_copy.unlink()
            except OSError:
                pass
        if extracted_to is not None:
            import shutil
            try:
                shutil.rmtree(extracted_to, ignore_errors=True)
            except OSError:
                pass
    return out


def _find_cookies_db(root: Path) -> Optional[Path]:
    """Walk a profile bundle and return the first Chrome Cookies DB found.

    Modern Chromium often stores the DB at ``Default/Network/Cookies`` while
    older bundles used ``Default/Cookies``. AdsPower backups in the wild use
    both layouts, so we probe the common explicit locations first and only then
    fall back to a broad recursive search.
    """
    explicit_candidates = [
        root / "Default" / "Network" / "Cookies",
        root / "Default" / "Cookies",
        root / "Profile 1" / "Network" / "Cookies",
        root / "Profile 1" / "Cookies",
        root / "Profile 2" / "Network" / "Cookies",
        root / "Profile 2" / "Cookies",
        root / "Profile 3" / "Network" / "Cookies",
        root / "Profile 3" / "Cookies",
    ]
    for cand in explicit_candidates:
        if cand.exists():
            return cand

    for cand in root.rglob("Cookies"):
        parent = cand.parent.name
        grandparent = cand.parent.parent.name if cand.parent.parent else ""
        if parent in ("Default", "Profile 1", "Profile 2", "Profile 3"):
            return cand
        if parent == "Network" and grandparent in ("Default", "Profile 1", "Profile 2", "Profile 3"):
            return cand
        if grandparent.endswith(".app"):
            return cand
    matches = list(root.rglob("Cookies"))
    return matches[0] if matches else None


# ---------------------------------------------------------------------------
# Full-profile state — LocalStorage + IndexedDB
# ---------------------------------------------------------------------------
#
# Chrome ≥ 61 stores ``window.localStorage`` per origin in LevelDB files
# under ``<profile>/Default/Local Storage/leveldb/`` and IndexedDB under
# ``<profile>/Default/IndexedDB/<origin>.indexeddb.leveldb/``. Both formats
# use Snappy-compressed LevelDB with V8 structured-clone values for IndexedDB.
#
# Rather than re-implement Chrome's LevelDB decoder (which is fragile,
# version-coupled, and Windows-hostile due to plyvel's native deps), we
# let Chromium read its own files natively: copy the relevant directories
# from the .adb bundle into Playwright's ``user_data_dir`` before the first
# launch and Chromium handles them as if it had written them itself.
#
# Reference: https://www.browserforensics.app/en/blog/chrome-local-storage-and-indexeddb


def find_profile_default_dir(root: Path) -> Optional[Path]:
    """Locate the ``Default/`` profile dir inside an extracted bundle.

    Chrome names the primary profile folder ``Default``; AdsPower's exported
    bundles usually keep this name verbatim inside an extra wrapper folder
    (e.g. ``<bundle>/profile_xxx/Default``). We walk one level deep so we
    find the real ``Default`` even when the bundle is wrapped.

    Returns ``None`` if no Default/ folder exists.
    """
    # First pass: exact match at root
    direct = root / "Default"
    if direct.is_dir():
        return direct
    # Second pass: look for Default/ at depth 1 (typical AdsPower wrap)
    for cand in root.glob("*/Default"):
        if cand.is_dir():
            return cand
    # Third pass: any Default/ anywhere (with sanity check for Local Storage)
    for cand in root.rglob("Default"):
        if cand.is_dir() and (cand / "Local Storage").exists():
            return cand
    return None


def find_local_storage_dir(default_dir: Path) -> Optional[Path]:
    """Return the LevelDB directory used by ``window.localStorage`` if present."""
    if not default_dir.is_dir():
        return None
    cand = default_dir / "Local Storage" / "leveldb"
    if cand.is_dir():
        return cand
    return None


def find_indexeddb_dir(default_dir: Path) -> Optional[Path]:
    """Return the IndexedDB directory used by ``window.indexedDB`` if present."""
    if not default_dir.is_dir():
        return None
    cand = default_dir / "IndexedDB"
    if cand.is_dir():
        return cand
    return None


def find_webstorage_dir(default_dir: Path) -> Optional[Path]:
    """Return the Chromium ``WebStorage`` directory if present.

    Some AdsPower backups keep IndexedDB state nested under
    ``Default/WebStorage/<origin-id>/IndexedDB`` instead of the simpler
    ``Default/IndexedDB`` layout. Copying the whole WebStorage tree preserves
    that state without needing to decode Chromium internals.
    """
    if not default_dir.is_dir():
        return None
    cand = default_dir / "WebStorage"
    if cand.is_dir():
        return cand
    return None


def extract_adspower_bundle(src: Union[str, Path], dest_dir: Union[str, Path]) -> Path:
    """Extract an AdsPower bundle (folder, ``.zip`` or ``.tar.gz``) to ``dest_dir``.

    Always extracts into a clean directory — if ``dest_dir`` already exists, it's
    wiped first. Returns the resolved ``dest_dir`` path.

    Supports three bundle shapes:

    - **Folder**: ``src`` is a directory; its contents are copied into ``dest_dir``.
    - **Zip**: ``.zip`` archive; ``zipfile.extractall`` into ``dest_dir``.
    - **Tar**: ``.tar`` / ``.tgz`` / ``.tar.gz`` archive; ``tarfile.extractall``.

    Raises ``ValueError`` for unknown shapes.
    """
    import shutil

    src = Path(src)
    dest = Path(dest_dir)
    if dest.exists():
        shutil.rmtree(dest)

    if src.is_dir():
        # Folder: copytree creates dest itself, do NOT mkdir first.
        shutil.copytree(src, dest)
    elif src.suffix.lower() == ".zip":
        dest.mkdir(parents=True, exist_ok=True)
        with zipfile.ZipFile(src, "r") as zf:
            zf.extractall(dest)
    elif src.suffix.lower() in (".tar", ".tgz") or src.name.endswith(".tar.gz"):
        dest.mkdir(parents=True, exist_ok=True)
        with tarfile.open(src, "r:*") as tf:
            tf.extractall(dest)
    else:
        raise ValueError(
            f"Unsupported AdsPower bundle format: {src!s} "
            "(expected a folder, .zip, .tar, .tgz or .tar.gz)"
        )
    return dest


def apply_initial_state_to_user_data(
    source_default: Union[str, Path],
    target_user_data: Union[str, Path],
    *,
    force: bool = False,
) -> Dict[str, str]:
    """Copy ``Local Storage/leveldb`` and ``IndexedDB`` from a source Chrome
    profile directory into Playwright's ``user_data_dir``.

    Chrome reads its own LevelDB format natively, so copying the directories
    verbatim works without needing a LevelDB parser.

    Args:
        source_default: Path to the source ``Default/`` folder inside an
            extracted .adb bundle (see ``find_profile_default_dir``).
        target_user_data: Path to the Playwright ``user_data_dir``. The
            function creates a ``Default/`` subfolder inside it if missing
            and copies the two subdirs there.
        force: If True, overwrite existing ``Local Storage/leveldb`` /
            ``IndexedDB`` folders inside the target. Default False — skip
            if already present so user-accumulated state isn't lost.

    Returns:
        Dict mapping ``"local_storage"`` / ``"indexeddb"`` / ``"webstorage"``
        to the destination path, for each directory that was actually copied.
        Missing source dirs are silently skipped (some profiles have no
        IndexedDB, etc.).
    """
    import shutil

    source_default = Path(source_default)
    target_user_data = Path(target_user_data)
    target_default = target_user_data / "Default"
    target_default.mkdir(parents=True, exist_ok=True)

    copied: Dict[str, str] = {}

    ls_src = find_local_storage_dir(source_default)
    if ls_src is not None and ls_src.exists():
        ls_dst = target_default / "Local Storage" / "leveldb"
        if not ls_dst.exists() or force:
            ls_dst.parent.mkdir(parents=True, exist_ok=True)
            if ls_dst.exists() and force:
                shutil.rmtree(ls_dst)
            shutil.copytree(ls_src, ls_dst)
            copied["local_storage"] = str(ls_dst)

    idb_src = find_indexeddb_dir(source_default)
    if idb_src is not None and idb_src.exists():
        idb_dst = target_default / "IndexedDB"
        if not idb_dst.exists() or force:
            if idb_dst.exists() and force:
                shutil.rmtree(idb_dst)
            shutil.copytree(idb_src, idb_dst)
            copied["indexeddb"] = str(idb_dst)

    webstorage_src = find_webstorage_dir(source_default)
    if webstorage_src is not None and webstorage_src.exists():
        webstorage_dst = target_default / "WebStorage"
        if not webstorage_dst.exists() or force:
            if webstorage_dst.exists() and force:
                shutil.rmtree(webstorage_dst)
            shutil.copytree(webstorage_src, webstorage_dst)
            copied["webstorage"] = str(webstorage_dst)

    return copied


def prepare_adspower_import(
    src: Union[str, Path],
    dest_root: Union[str, Path],
    profile_id: str,
) -> Dict[str, Any]:
    """One-shot helper: extract ``src`` to ``dest_root/<profile_id>/``,
    parse cookies, and return everything the caller needs to finish the
    import.

    Returns a dict with::

        {
            "extracted_path": "<dest_root>/<profile_id>",
            "default_dir": "<dest_root>/<profile_id>/Default"  # or None
            "cookies": [Cookie, ...]
        }
    """
    dest = Path(dest_root) / profile_id
    extract_adspower_bundle(src, dest)
    default_dir = find_profile_default_dir(dest)

    cookies: List[Cookie] = []
    cookies_db = _find_cookies_db(dest) if default_dir is not None else None
    if cookies_db is not None:
        # Reuse the same private parser the legacy import_adspower_profile uses.
        cookies = _read_cookies_db(cookies_db)
    return {
        "extracted_path": str(dest),
        "default_dir": str(default_dir) if default_dir else None,
        "cookies": cookies,
    }


def _read_cookies_db(cookies_db: Path) -> List[Cookie]:
    """Open a Chrome Cookies SQLite DB and return a list of ``Cookie``."""
    import shutil
    import tempfile

    conn = None
    tmp_copy: Optional[Path] = None
    try:
        try:
            conn = sqlite3.connect(f"file:{cookies_db}?mode=ro", uri=True)
        except sqlite3.OperationalError:
            # File might be locked; copy to a temp file and open that.
            tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".db")
            tmp.close()
            shutil.copy2(cookies_db, tmp.name)
            tmp_copy = Path(tmp.name)
            conn = sqlite3.connect(str(tmp_copy))
        return _read_cookies_from_conn(conn)
    finally:
        if conn is not None:
            try:
                conn.close()
            except Exception:
                pass
        if tmp_copy is not None:
            try:
                tmp_copy.unlink()
            except OSError:
                pass


def _read_cookies_from_conn(conn: sqlite3.Connection) -> List[Cookie]:
    out: List[Cookie] = []
    cur = conn.cursor()
    # Determine if samesite column exists (older Chrome schemas don't)
    cols = {row[1] for row in cur.execute("PRAGMA table_info(cookies)").fetchall()}
    has_samesite = "samesite" in cols
    has_persist = "is_persistent" in cols
    # Chrome stores expires_utc in microseconds since 1601-01-01 (Windows epoch).
    # Web epoch starts 1970-01-01. The delta is 11644473600 seconds.
    WIN_EPOCH_DELTA = 11644473600
    rows = cur.execute(
        "SELECT name, value, host_key, path, expires_utc, is_secure, is_httponly%s%s FROM cookies"
        % (", samesite" if has_samesite else "", ", is_persistent" if has_persist else "")
    ).fetchall()
    for row in rows:
        name, value, host_key, path, expires_utc, is_secure, is_httponly = row[:7]
        samesite = row[7] if has_samesite else None
        is_persistent = row[8] if has_persist else None
        # Convert Chrome microseconds → Unix seconds
        try:
            exp = (int(expires_utc) / 1_000_000) - WIN_EPOCH_DELTA if int(expires_utc) > 0 else -1
        except (TypeError, ValueError):
            exp = -1
        if not is_persistent:
            exp = -1
        out.append(
            Cookie(
                name=name or "",
                value=value or "",
                domain=host_key or "",
                path=path or "/",
                expires=exp,
                secure=bool(is_secure),
                http_only=bool(is_httponly),
                same_site=_normalize_samesite(str(samesite) if samesite is not None else None),
            )
        )
    return out


# ---------------------------------------------------------------------------
# Format writers
# ---------------------------------------------------------------------------


def export_cookies_netscape(cookies: List[Cookie]) -> str:
    """Serialise cookies back into Netscape ``cookies.txt`` format."""
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by antidetect-local",
        "# https://curl.haxx.ru/rfc/cookie_spec.html",
        "",
    ]
    for c in cookies:
        domain = c.domain or ""
        flag = "TRUE"  # we always include subdomains
        path = c.path or "/"
        secure = "TRUE" if c.secure else "FALSE"
        exp = int(c.expires) if c.expires and c.expires > 0 else 0
        # Netscape convention: 0 = session cookie
        lines.append("\t".join([domain, flag, path, secure, str(exp), c.name, c.value]))
    return "\n".join(lines) + "\n"


def export_cookies_json(cookies: List[Cookie]) -> str:
    """Serialise cookies to Playwright JSON format."""
    return json.dumps([c.to_playwright() for c in cookies], indent=2, ensure_ascii=False)


# ---------------------------------------------------------------------------
# Convenience: round-trip via path
# ---------------------------------------------------------------------------


def import_cookies(path: Union[str, Path]) -> List[Cookie]:
    """Auto-detect format by extension and parse.

    - ``.txt`` → Netscape
    - ``.json`` → Playwright/CDP JSON
    - ``.adb`` / ``.zip`` / ``.tar.gz`` / directory → AdsPower bundle
    """
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(p)
    if p.is_dir() or p.suffix.lower() in (".adb", ".zip", ".tar", ".tgz"):
        return import_adspower_profile(p)
    if p.suffix.lower() == ".json":
        return import_cookies_json(p.read_text(encoding="utf-8"))
    # default: Netscape
    return import_cookies_netscape(p.read_text(encoding="utf-8"))